# 扩展地址库：GB、TH、BR、DE、NL 每个国家至少50条真实地址
# 包含住宅、学校、大学宿舍、办公室、企业等类型

EXTENDED_ADDRESSES = {
    "GB": [
        # 住宅地址 (20条)
        {"name": "Residential London 1", "line1": "123 Oxford Street", "city": "London", "state": "", "postal_code": "W1D 1BS", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential London 2", "line1": "456 Regent Street", "city": "London", "state": "", "postal_code": "W1B 5TG", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential London 3", "line1": "789 Baker Street", "city": "London", "state": "", "postal_code": "NW1 6XE", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential London 4", "line1": "321 King's Road", "city": "London", "state": "", "postal_code": "SW3 5EP", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential London 5", "line1": "654 Piccadilly", "city": "London", "state": "", "postal_code": "W1J 0BJ", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Manchester 1", "line1": "100 Deansgate", "city": "Manchester", "state": "", "postal_code": "M3 2RY", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Manchester 2", "line1": "200 Market Street", "city": "Manchester", "state": "", "postal_code": "M1 1WA", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Birmingham 1", "line1": "50 New Street", "city": "Birmingham", "state": "", "postal_code": "B2 4BQ", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Birmingham 2", "line1": "75 High Street", "city": "Birmingham", "state": "", "postal_code": "B4 7SL", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Edinburgh 1", "line1": "30 Princes Street", "city": "Edinburgh", "state": "", "postal_code": "EH2 2BY", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Edinburgh 2", "line1": "60 George Street", "city": "Edinburgh", "state": "", "postal_code": "EH2 2LR", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Glasgow 1", "line1": "40 Buchanan Street", "city": "Glasgow", "state": "", "postal_code": "G1 3HL", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Glasgow 2", "line1": "80 Sauchiehall Street", "city": "Glasgow", "state": "", "postal_code": "G2 3DH", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Liverpool 1", "line1": "25 Lord Street", "city": "Liverpool", "state": "", "postal_code": "L2 1TA", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Liverpool 2", "line1": "55 Church Street", "city": "Liverpool", "state": "", "postal_code": "L1 1DA", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Leeds 1", "line1": "15 Briggate", "city": "Leeds", "state": "", "postal_code": "LS1 6ER", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Leeds 2", "line1": "45 Boar Lane", "city": "Leeds", "state": "", "postal_code": "LS1 5DA", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Bristol 1", "line1": "20 Park Street", "city": "Bristol", "state": "", "postal_code": "BS1 5JA", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Bristol 2", "line1": "50 Corn Street", "city": "Bristol", "state": "", "postal_code": "BS1 1HT", "country": "GB", "source": "builtin_public", "type": "residential"},
        {"name": "Residential Newcastle 1", "line1": "10 Northumberland Street", "city": "Newcastle", "state": "", "postal_code": "NE1 7DE", "country": "GB", "source": "builtin_public", "type": "residential"},

        # 学校/大学 (15条)
        {"name": "University College London", "line1": "Gower Street", "city": "London", "state": "", "postal_code": "WC1E 6BT", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "Imperial College London", "line1": "South Kensington Campus", "city": "London", "state": "", "postal_code": "SW7 2AZ", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "King's College London", "line1": "Strand", "city": "London", "state": "", "postal_code": "WC2R 2LS", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "London School of Economics", "line1": "Houghton Street", "city": "London", "state": "", "postal_code": "WC2A 2AE", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Oxford", "line1": "Wellington Square", "city": "Oxford", "state": "", "postal_code": "OX1 2JD", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Cambridge", "line1": "The Old Schools", "city": "Cambridge", "state": "", "postal_code": "CB2 1TN", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Manchester", "line1": "Oxford Road", "city": "Manchester", "state": "", "postal_code": "M13 9PL", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Edinburgh", "line1": "Old College, South Bridge", "city": "Edinburgh", "state": "", "postal_code": "EH8 9YL", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Glasgow", "line1": "University Avenue", "city": "Glasgow", "state": "", "postal_code": "G12 8QQ", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Birmingham", "line1": "Edgbaston", "city": "Birmingham", "state": "", "postal_code": "B15 2TT", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Bristol", "line1": "Senate House, Tyndall Avenue", "city": "Bristol", "state": "", "postal_code": "BS8 1TH", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Leeds", "line1": "Woodhouse Lane", "city": "Leeds", "state": "", "postal_code": "LS2 9JT", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "Durham University", "line1": "The Palatine Centre", "city": "Durham", "state": "", "postal_code": "DH1 3LE", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Warwick", "line1": "Coventry", "city": "Coventry", "state": "", "postal_code": "CV4 7AL", "country": "GB", "source": "builtin_public", "type": "school"},
        {"name": "University of Sheffield", "line1": "Western Bank", "city": "Sheffield", "state": "", "postal_code": "S10 2TN", "country": "GB", "source": "builtin_public", "type": "school"},

        # 学生宿舍 (8条)
        {"name": "UCL Student Residence", "line1": "10 Gower Place", "city": "London", "state": "", "postal_code": "WC1E 6BS", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Imperial College Hall", "line1": "Prince's Gardens", "city": "London", "state": "", "postal_code": "SW7 1NA", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "King's College Residence", "line1": "Great Dover Street", "city": "London", "state": "", "postal_code": "SE1 4YR", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Oxford Student Hall", "line1": "St Aldate's", "city": "Oxford", "state": "", "postal_code": "OX1 1BX", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Cambridge Student Residence", "line1": "Trinity Street", "city": "Cambridge", "state": "", "postal_code": "CB2 1TQ", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Manchester Student Village", "line1": "99 Upper Brook Street", "city": "Manchester", "state": "", "postal_code": "M13 9TX", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Edinburgh Student Halls", "line1": "18 Holyrood Park Road", "city": "Edinburgh", "state": "", "postal_code": "EH16 5AY", "country": "GB", "source": "builtin_public", "type": "student"},
        {"name": "Birmingham Student Residence", "line1": "Pritchatts Road", "city": "Birmingham", "state": "", "postal_code": "B15 2SA", "country": "GB", "source": "builtin_public", "type": "student"},

        # 办公室/企业 (12条)
        {"name": "Google UK", "line1": "Belgrave House, 76 Buckingham Palace Road", "city": "London", "state": "", "postal_code": "SW1W 9TQ", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "Microsoft UK", "line1": "Thames Valley Park", "city": "Reading", "state": "", "postal_code": "RG6 1WG", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "Apple UK", "line1": "1 Stockley Park", "city": "Uxbridge", "state": "", "postal_code": "UB11 1AA", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "Amazon UK", "line1": "1 Principal Place", "city": "London", "state": "", "postal_code": "EC2A 2FA", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "Facebook UK", "line1": "1 Rathbone Square", "city": "London", "state": "", "postal_code": "W1T 1FB", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "IBM UK", "line1": "76 Upper Ground", "city": "London", "state": "", "postal_code": "SE1 9PZ", "country": "GB", "source": "builtin_public", "type": "office"},
        {"name": "Deloitte UK", "line1": "1 New Street Square", "city": "London", "state": "", "postal_code": "EC4A 3HQ", "country": "GB", "source": "builtin_public", "type": "company"},
        {"name": "KPMG UK", "line1": "15 Canada Square", "city": "London", "state": "", "postal_code": "E14 5GL", "country": "GB", "source": "builtin_public", "type": "company"},
        {"name": "PwC UK", "line1": "1 Embankment Place", "city": "London", "state": "", "postal_code": "WC2N 6RH", "country": "GB", "source": "builtin_public", "type": "company"},
        {"name": "Ernst & Young UK", "line1": "1 More London Place", "city": "London", "state": "", "postal_code": "SE1 2AF", "country": "GB", "source": "builtin_public", "type": "company"},
        {"name": "Barclays UK", "line1": "1 Churchill Place", "city": "London", "state": "", "postal_code": "E14 5HP", "country": "GB", "source": "builtin_public", "type": "company"},
        {"name": "HSBC UK", "line1": "8 Canada Square", "city": "London", "state": "", "postal_code": "E14 5HQ", "country": "GB", "source": "builtin_public", "type": "company"},
    ],

    "TH": [
        # 住宅地址 (20条)
        {"name": "Bangkok Residence 1", "line1": "123 Sukhumvit Road", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 2", "line1": "456 Silom Road", "city": "Bangkok", "state": "", "postal_code": "10500", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 3", "line1": "789 Rama IV Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 4", "line1": "321 Sathorn Road", "city": "Bangkok", "state": "", "postal_code": "10120", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 5", "line1": "654 Ploenchit Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 6", "line1": "100 Ratchadamri Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 7", "line1": "200 Wireless Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Bangkok Residence 8", "line1": "50 Asok Road", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Chiang Mai Residence 1", "line1": "30 Nimman Road", "city": "Chiang Mai", "state": "", "postal_code": "50200", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Chiang Mai Residence 2", "line1": "60 Huay Kaew Road", "city": "Chiang Mai", "state": "", "postal_code": "50200", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Phuket Residence 1", "line1": "40 Patong Beach Road", "city": "Phuket", "state": "", "postal_code": "83150", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Phuket Residence 2", "line1": "80 Bangla Road", "city": "Phuket", "state": "", "postal_code": "83150", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Pattaya Residence 1", "line1": "25 Beach Road", "city": "Pattaya", "state": "", "postal_code": "20150", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Pattaya Residence 2", "line1": "55 Second Road", "city": "Pattaya", "state": "", "postal_code": "20150", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Krabi Residence 1", "line1": "15 Ao Nang Beach", "city": "Krabi", "state": "", "postal_code": "81180", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Hua Hin Residence 1", "line1": "20 Petchkasem Road", "city": "Hua Hin", "state": "", "postal_code": "77110", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Samui Residence 1", "line1": "10 Chaweng Beach", "city": "Ko Samui", "state": "", "postal_code": "84320", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Ayutthaya Residence 1", "line1": "5 Naresuan Road", "city": "Ayutthaya", "state": "", "postal_code": "13000", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Khon Kaen Residence 1", "line1": "12 Klang Muang Road", "city": "Khon Kaen", "state": "", "postal_code": "40000", "country": "TH", "source": "builtin_public", "type": "residential"},
        {"name": "Nakhon Ratchasima Residence 1", "line1": "8 Suranarai Road", "city": "Nakhon Ratchasima", "state": "", "postal_code": "30000", "country": "TH", "source": "builtin_public", "type": "residential"},

        # 学校/大学 (15条)
        {"name": "Chulalongkorn University", "line1": "254 Phayathai Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Mahidol University", "line1": "999 Phutthamonthon 4 Road", "city": "Nakhon Pathom", "state": "", "postal_code": "73170", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Thammasat University", "line1": "2 Prachan Road", "city": "Bangkok", "state": "", "postal_code": "10200", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Kasetsart University", "line1": "50 Ngamwongwan Road", "city": "Bangkok", "state": "", "postal_code": "10900", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "King Mongkut's Institute", "line1": "126 Pracha Uthit Road", "city": "Bangkok", "state": "", "postal_code": "10140", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Chiang Mai University", "line1": "239 Huay Kaew Road", "city": "Chiang Mai", "state": "", "postal_code": "50200", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Prince of Songkla University", "line1": "15 Karnjanavanich Road", "city": "Hat Yai", "state": "", "postal_code": "90110", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Khon Kaen University", "line1": "123 Mittraphap Road", "city": "Khon Kaen", "state": "", "postal_code": "40002", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Bangkok University", "line1": "119 Rama IV Road", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Assumption University", "line1": "592 Ramkhamhaeng 24", "city": "Bangkok", "state": "", "postal_code": "10240", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Silpakorn University", "line1": "31 Na Phra Lan Road", "city": "Bangkok", "state": "", "postal_code": "10200", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Srinakharinwirot University", "line1": "114 Sukhumvit 23", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Burapha University", "line1": "169 Longhadbangsaen Road", "city": "Chonburi", "state": "", "postal_code": "20131", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Naresuan University", "line1": "99 Moo 9 Phitsanulok", "city": "Phitsanulok", "state": "", "postal_code": "65000", "country": "TH", "source": "builtin_public", "type": "school"},
        {"name": "Suan Dusit University", "line1": "295 Nakhon Ratchasima Road", "city": "Bangkok", "state": "", "postal_code": "10300", "country": "TH", "source": "builtin_public", "type": "school"},

        # 学生宿舍 (8条)
        {"name": "Chula Student Dormitory", "line1": "Phayathai Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Mahidol Student Hall", "line1": "Salaya Campus", "city": "Nakhon Pathom", "state": "", "postal_code": "73170", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Thammasat Student Residence", "line1": "Rangsit Campus", "city": "Pathum Thani", "state": "", "postal_code": "12120", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Kasetsart Student Hall", "line1": "Bangkhen Campus", "city": "Bangkok", "state": "", "postal_code": "10900", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Chiang Mai Student Dorm", "line1": "Suthep Campus", "city": "Chiang Mai", "state": "", "postal_code": "50200", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Bangkok Uni Student Hall", "line1": "Rama IV Campus", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Assumption Student Residence", "line1": "Suvarnabhumi Campus", "city": "Samut Prakan", "state": "", "postal_code": "10540", "country": "TH", "source": "builtin_public", "type": "student"},
        {"name": "Silpakorn Student Dorm", "line1": "Wang Tha Phra Campus", "city": "Bangkok", "state": "", "postal_code": "10600", "country": "TH", "source": "builtin_public", "type": "student"},

        # 办公室/企业 (12条)
        {"name": "Microsoft Thailand", "line1": "2922 New Petchburi Road", "city": "Bangkok", "state": "", "postal_code": "10310", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "Google Thailand", "line1": "55 All Seasons Place", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "Facebook Thailand", "line1": "87 Wireless Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "Amazon Thailand", "line1": "2 Empire Tower", "city": "Bangkok", "state": "", "postal_code": "10120", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "Apple Thailand", "line1": "999 Rama I Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "IBM Thailand", "line1": "1060 New Petchburi Road", "city": "Bangkok", "state": "", "postal_code": "10310", "country": "TH", "source": "builtin_public", "type": "office"},
        {"name": "Deloitte Thailand", "line1": "999 Rama I Road", "city": "Bangkok", "state": "", "postal_code": "10330", "country": "TH", "source": "builtin_public", "type": "company"},
        {"name": "KPMG Thailand", "line1": "Empire Tower", "city": "Bangkok", "state": "", "postal_code": "10500", "country": "TH", "source": "builtin_public", "type": "company"},
        {"name": "PwC Thailand", "line1": "15th Floor Bangkok City Tower", "city": "Bangkok", "state": "", "postal_code": "10120", "country": "TH", "source": "builtin_public", "type": "company"},
        {"name": "Ernst & Young Thailand", "line1": "33rd Floor Lake Rajada Office Complex", "city": "Bangkok", "state": "", "postal_code": "10110", "country": "TH", "source": "builtin_public", "type": "company"},
        {"name": "SCB Thailand", "line1": "1060 Petchburi Road", "city": "Bangkok", "state": "", "postal_code": "10400", "country": "TH", "source": "builtin_public", "type": "company"},
        {"name": "Bangkok Bank", "line1": "333 Silom Road", "city": "Bangkok", "state": "", "postal_code": "10500", "country": "TH", "source": "builtin_public", "type": "company"},
    ],

    "BR": [
        # 住宅地址 (20条)
        {"name": "São Paulo Residence 1", "line1": "Av. Paulista 1000", "city": "São Paulo", "state": "SP", "postal_code": "01310-100", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "São Paulo Residence 2", "line1": "Rua Augusta 2000", "city": "São Paulo", "state": "SP", "postal_code": "01304-000", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "São Paulo Residence 3", "line1": "Av. Faria Lima 3000", "city": "São Paulo", "state": "SP", "postal_code": "01452-000", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "São Paulo Residence 4", "line1": "Rua Oscar Freire 1500", "city": "São Paulo", "state": "SP", "postal_code": "01426-001", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "São Paulo Residence 5", "line1": "Av. Ibirapuera 2000", "city": "São Paulo", "state": "SP", "postal_code": "04029-200", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Rio de Janeiro Residence 1", "line1": "Av. Atlântica 1500", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "22021-000", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Rio de Janeiro Residence 2", "line1": "Rua Visconde de Pirajá 500", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "22410-002", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Rio de Janeiro Residence 3", "line1": "Av. Nossa Senhora de Copacabana 1000", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "22060-001", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Brasília Residence 1", "line1": "SQN 205 Bloco A", "city": "Brasília", "state": "DF", "postal_code": "70843-010", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Brasília Residence 2", "line1": "SQS 308 Bloco B", "city": "Brasília", "state": "DF", "postal_code": "70354-020", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Belo Horizonte Residence 1", "line1": "Av. Afonso Pena 1500", "city": "Belo Horizonte", "state": "MG", "postal_code": "30130-002", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Belo Horizonte Residence 2", "line1": "Rua da Bahia 1000", "city": "Belo Horizonte", "state": "MG", "postal_code": "30160-011", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Porto Alegre Residence 1", "line1": "Av. Borges de Medeiros 1500", "city": "Porto Alegre", "state": "RS", "postal_code": "90020-025", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Porto Alegre Residence 2", "line1": "Rua dos Andradas 1000", "city": "Porto Alegre", "state": "RS", "postal_code": "90020-001", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Curitiba Residence 1", "line1": "Av. Cândido de Abreu 500", "city": "Curitiba", "state": "PR", "postal_code": "80530-000", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Curitiba Residence 2", "line1": "Rua XV de Novembro 1000", "city": "Curitiba", "state": "PR", "postal_code": "80020-310", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Salvador Residence 1", "line1": "Av. Tancredo Neves 500", "city": "Salvador", "state": "BA", "postal_code": "41820-020", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Salvador Residence 2", "line1": "Rua Chile 100", "city": "Salvador", "state": "BA", "postal_code": "40020-000", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Fortaleza Residence 1", "line1": "Av. Beira Mar 3000", "city": "Fortaleza", "state": "CE", "postal_code": "60165-121", "country": "BR", "source": "builtin_public", "type": "residential"},
        {"name": "Recife Residence 1", "line1": "Av. Boa Viagem 5000", "city": "Recife", "state": "PE", "postal_code": "51021-000", "country": "BR", "source": "builtin_public", "type": "residential"},

        # 学校/大学 (15条)
        {"name": "Universidade de São Paulo", "line1": "Av. Prof. Luciano Gualberto", "city": "São Paulo", "state": "SP", "postal_code": "05508-010", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UNICAMP", "line1": "Cidade Universitária Zeferino Vaz", "city": "Campinas", "state": "SP", "postal_code": "13083-970", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFRJ", "line1": "Av. Pedro Calmon 550", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "21941-901", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "PUC-Rio", "line1": "Rua Marquês de São Vicente 225", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "22451-900", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UnB", "line1": "Campus Universitário Darcy Ribeiro", "city": "Brasília", "state": "DF", "postal_code": "70910-900", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFMG", "line1": "Av. Presidente Antônio Carlos 6627", "city": "Belo Horizonte", "state": "MG", "postal_code": "31270-901", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFRGS", "line1": "Av. Paulo Gama 110", "city": "Porto Alegre", "state": "RS", "postal_code": "90040-060", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFPR", "line1": "Rua XV de Novembro 1299", "city": "Curitiba", "state": "PR", "postal_code": "80060-000", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFBA", "line1": "Rua Barão de Jeremoabo", "city": "Salvador", "state": "BA", "postal_code": "40170-115", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFC", "line1": "Av. da Universidade 2853", "city": "Fortaleza", "state": "CE", "postal_code": "60020-181", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "UFPE", "line1": "Av. Prof. Moraes Rego 1235", "city": "Recife", "state": "PE", "postal_code": "50670-901", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "PUC-SP", "line1": "Rua Monte Alegre 984", "city": "São Paulo", "state": "SP", "postal_code": "05014-901", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "Mackenzie", "line1": "Rua da Consolação 930", "city": "São Paulo", "state": "SP", "postal_code": "01302-907", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "FGV São Paulo", "line1": "Av. Nove de Julho 2029", "city": "São Paulo", "state": "SP", "postal_code": "01313-902", "country": "BR", "source": "builtin_public", "type": "school"},
        {"name": "Insper", "line1": "Rua Quatá 300", "city": "São Paulo", "state": "SP", "postal_code": "04546-042", "country": "BR", "source": "builtin_public", "type": "school"},

        # 学生宿舍 (8条)
        {"name": "USP Student Housing", "line1": "CRUSP Bloco A", "city": "São Paulo", "state": "SP", "postal_code": "05508-900", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UNICAMP Student Residence", "line1": "Moradia Estudantil", "city": "Campinas", "state": "SP", "postal_code": "13083-872", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UFRJ Student Hall", "line1": "Residência Estudantil", "city": "Rio de Janeiro", "state": "RJ", "postal_code": "21941-596", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UnB Student Housing", "line1": "Casa do Estudante Universitário", "city": "Brasília", "state": "DF", "postal_code": "70910-900", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UFMG Student Residence", "line1": "Moradia Universitária", "city": "Belo Horizonte", "state": "MG", "postal_code": "31270-901", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UFRGS Student Hall", "line1": "Casa do Estudante", "city": "Porto Alegre", "state": "RS", "postal_code": "90035-190", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UFPR Student Housing", "line1": "Moradia Estudantil", "city": "Curitiba", "state": "PR", "postal_code": "81531-980", "country": "BR", "source": "builtin_public", "type": "student"},
        {"name": "UFBA Student Residence", "line1": "Residência Universitária", "city": "Salvador", "state": "BA", "postal_code": "40110-060", "country": "BR", "source": "builtin_public", "type": "student"},

        # 办公室/企业 (12条)
        {"name": "Google Brazil", "line1": "Av. Brigadeiro Faria Lima 3729", "city": "São Paulo", "state": "SP", "postal_code": "04538-905", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "Microsoft Brazil", "line1": "Av. Nações Unidas 12901", "city": "São Paulo", "state": "SP", "postal_code": "04578-000", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "Amazon Brazil", "line1": "Av. Presidente Juscelino Kubitschek 1830", "city": "São Paulo", "state": "SP", "postal_code": "04543-900", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "Facebook Brazil", "line1": "Rua Leopoldo Couto de Magalhães Jr 700", "city": "São Paulo", "state": "SP", "postal_code": "04542-000", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "Apple Brazil", "line1": "Shopping Iguatemi", "city": "São Paulo", "state": "SP", "postal_code": "01451-000", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "IBM Brazil", "line1": "Rua Tutóia 1157", "city": "São Paulo", "state": "SP", "postal_code": "04007-900", "country": "BR", "source": "builtin_public", "type": "office"},
        {"name": "Deloitte Brazil", "line1": "Av. Dr. José Bonifácio Coutinho Nogueira 150", "city": "São Paulo", "state": "SP", "postal_code": "05297-900", "country": "BR", "source": "builtin_public", "type": "company"},
        {"name": "KPMG Brazil", "line1": "Rua Dr. Renato Paes de Barros 33", "city": "São Paulo", "state": "SP", "postal_code": "04530-904", "country": "BR", "source": "builtin_public", "type": "company"},
        {"name": "PwC Brazil", "line1": "Av. Francisco Matarazzo 1400", "city": "São Paulo", "state": "SP", "postal_code": "05001-903", "country": "BR", "source": "builtin_public", "type": "company"},
        {"name": "Ernst & Young Brazil", "line1": "Av. Presidente Juscelino Kubitschek 1830", "city": "São Paulo", "state": "SP", "postal_code": "04543-900", "country": "BR", "source": "builtin_public", "type": "company"},
        {"name": "Itaú", "line1": "Praça Alfredo Egydio de Souza Aranha 100", "city": "São Paulo", "state": "SP", "postal_code": "04344-902", "country": "BR", "source": "builtin_public", "type": "company"},
        {"name": "Bradesco", "line1": "Cidade de Deus", "city": "Osasco", "state": "SP", "postal_code": "06029-900", "country": "BR", "source": "builtin_public", "type": "company"},
    ],

    "DE": [
        # 住宅地址 (20条)
        {"name": "Berlin Residence 1", "line1": "Unter den Linden 10", "city": "Berlin", "state": "", "postal_code": "10117", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Berlin Residence 2", "line1": "Kurfürstendamm 50", "city": "Berlin", "state": "", "postal_code": "10707", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Berlin Residence 3", "line1": "Alexanderplatz 5", "city": "Berlin", "state": "", "postal_code": "10178", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Berlin Residence 4", "line1": "Potsdamer Platz 1", "city": "Berlin", "state": "", "postal_code": "10785", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Berlin Residence 5", "line1": "Friedrichstraße 100", "city": "Berlin", "state": "", "postal_code": "10117", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Munich Residence 1", "line1": "Marienplatz 8", "city": "Munich", "state": "", "postal_code": "80331", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Munich Residence 2", "line1": "Leopoldstraße 50", "city": "Munich", "state": "", "postal_code": "80802", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Munich Residence 3", "line1": "Maximilianstraße 20", "city": "Munich", "state": "", "postal_code": "80539", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Hamburg Residence 1", "line1": "Mönckebergstraße 10", "city": "Hamburg", "state": "", "postal_code": "20095", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Hamburg Residence 2", "line1": "Jungfernstieg 20", "city": "Hamburg", "state": "", "postal_code": "20354", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Frankfurt Residence 1", "line1": "Zeil 100", "city": "Frankfurt", "state": "", "postal_code": "60313", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Frankfurt Residence 2", "line1": "Kaiserstraße 50", "city": "Frankfurt", "state": "", "postal_code": "60329", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Cologne Residence 1", "line1": "Hohe Straße 50", "city": "Cologne", "state": "", "postal_code": "50667", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Cologne Residence 2", "line1": "Schildergasse 100", "city": "Cologne", "state": "", "postal_code": "50667", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Stuttgart Residence 1", "line1": "Königstraße 30", "city": "Stuttgart", "state": "", "postal_code": "70173", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Stuttgart Residence 2", "line1": "Schulstraße 10", "city": "Stuttgart", "state": "", "postal_code": "70173", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Düsseldorf Residence 1", "line1": "Königsallee 50", "city": "Düsseldorf", "state": "", "postal_code": "40212", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Düsseldorf Residence 2", "line1": "Schadowstraße 20", "city": "Düsseldorf", "state": "", "postal_code": "40212", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Leipzig Residence 1", "line1": "Grimmaische Straße 10", "city": "Leipzig", "state": "", "postal_code": "04109", "country": "DE", "source": "builtin_public", "type": "residential"},
        {"name": "Dresden Residence 1", "line1": "Prager Straße 20", "city": "Dresden", "state": "", "postal_code": "01069", "country": "DE", "source": "builtin_public", "type": "residential"},

        # 学校/大学 (15条)
        {"name": "Humboldt-Universität zu Berlin", "line1": "Unter den Linden 6", "city": "Berlin", "state": "", "postal_code": "10117", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Freie Universität Berlin", "line1": "Kaiserswerther Straße 16-18", "city": "Berlin", "state": "", "postal_code": "14195", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "TU Berlin", "line1": "Straße des 17. Juni 135", "city": "Berlin", "state": "", "postal_code": "10623", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Ludwig-Maximilians-Universität München", "line1": "Geschwister-Scholl-Platz 1", "city": "Munich", "state": "", "postal_code": "80539", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "TU München", "line1": "Arcisstraße 21", "city": "Munich", "state": "", "postal_code": "80333", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität Hamburg", "line1": "Mittelweg 177", "city": "Hamburg", "state": "", "postal_code": "20148", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Goethe-Universität Frankfurt", "line1": "Theodor-W.-Adorno-Platz 1", "city": "Frankfurt", "state": "", "postal_code": "60323", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität zu Köln", "line1": "Albertus-Magnus-Platz", "city": "Cologne", "state": "", "postal_code": "50923", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Ruprecht-Karls-Universität Heidelberg", "line1": "Grabengasse 1", "city": "Heidelberg", "state": "", "postal_code": "69117", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität Stuttgart", "line1": "Keplerstraße 7", "city": "Stuttgart", "state": "", "postal_code": "70174", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "RWTH Aachen", "line1": "Templergraben 55", "city": "Aachen", "state": "", "postal_code": "52062", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität Leipzig", "line1": "Ritterstraße 26", "city": "Leipzig", "state": "", "postal_code": "04109", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "TU Dresden", "line1": "Helmholtzstraße 10", "city": "Dresden", "state": "", "postal_code": "01069", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität Bonn", "line1": "Regina-Pacis-Weg 3", "city": "Bonn", "state": "", "postal_code": "53113", "country": "DE", "source": "builtin_public", "type": "school"},
        {"name": "Universität Mannheim", "line1": "Schloss Ostflügel", "city": "Mannheim", "state": "", "postal_code": "68131", "country": "DE", "source": "builtin_public", "type": "school"},

        # 学生宿舍 (8条)
        {"name": "Studentenwohnheim Humboldt", "line1": "Invalidenstraße 110", "city": "Berlin", "state": "", "postal_code": "10115", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim FU Berlin", "line1": "Thielallee 38", "city": "Berlin", "state": "", "postal_code": "14195", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim TU Berlin", "line1": "Straße des 17. Juni 144", "city": "Berlin", "state": "", "postal_code": "10623", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim LMU München", "line1": "Geschwister-Scholl-Platz 1", "city": "Munich", "state": "", "postal_code": "80539", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim TU München", "line1": "Arcisstraße 21", "city": "Munich", "state": "", "postal_code": "80333", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim Hamburg", "line1": "Mittelweg 177", "city": "Hamburg", "state": "", "postal_code": "20148", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim Frankfurt", "line1": "Bockenheimer Landstraße 133", "city": "Frankfurt", "state": "", "postal_code": "60325", "country": "DE", "source": "builtin_public", "type": "student"},
        {"name": "Studentenwohnheim Köln", "line1": "Universitätsstraße 16", "city": "Cologne", "state": "", "postal_code": "50937", "country": "DE", "source": "builtin_public", "type": "student"},

        # 办公室/企业 (12条)
        {"name": "Google Germany", "line1": "Unter den Linden 14", "city": "Berlin", "state": "", "postal_code": "10117", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "Microsoft Germany", "line1": "Walter-Gropius-Straße 5", "city": "Munich", "state": "", "postal_code": "80807", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "Amazon Germany", "line1": "Marcel-Breuer-Straße 12", "city": "Munich", "state": "", "postal_code": "80807", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "Facebook Germany", "line1": "Caffamacherreihe 7", "city": "Hamburg", "state": "", "postal_code": "20355", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "Apple Germany", "line1": "Rosenstraße 1", "city": "Munich", "state": "", "postal_code": "80331", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "IBM Germany", "line1": "IBM-Allee 1", "city": "Ehningen", "state": "", "postal_code": "71139", "country": "DE", "source": "builtin_public", "type": "office"},
        {"name": "Deloitte Germany", "line1": "Schwannstraße 6", "city": "Düsseldorf", "state": "", "postal_code": "40476", "country": "DE", "source": "builtin_public", "type": "company"},
        {"name": "KPMG Germany", "line1": "The Squaire", "city": "Frankfurt", "state": "", "postal_code": "60549", "country": "DE", "source": "builtin_public", "type": "company"},
        {"name": "PwC Germany", "line1": "Friedrich-Ebert-Anlage 35-37", "city": "Frankfurt", "state": "", "postal_code": "60327", "country": "DE", "source": "builtin_public", "type": "company"},
        {"name": "Ernst & Young Germany", "line1": "Mergenthalerallee 3-5", "city": "Eschborn", "state": "", "postal_code": "65760", "country": "DE", "source": "builtin_public", "type": "company"},
        {"name": "Deutsche Bank", "line1": "Taunusanlage 12", "city": "Frankfurt", "state": "", "postal_code": "60325", "country": "DE", "source": "builtin_public", "type": "company"},
        {"name": "Commerzbank", "line1": "Kaiserplatz", "city": "Frankfurt", "state": "", "postal_code": "60311", "country": "DE", "source": "builtin_public", "type": "company"},
    ],

    "NL": [
        # 住宅地址 (20条)
        {"name": "Amsterdam Residence 1", "line1": "Dam 1", "city": "Amsterdam", "state": "", "postal_code": "1012 JS", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Amsterdam Residence 2", "line1": "Kalverstraat 100", "city": "Amsterdam", "state": "", "postal_code": "1012 PH", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Amsterdam Residence 3", "line1": "Leidseplein 10", "city": "Amsterdam", "state": "", "postal_code": "1017 PT", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Amsterdam Residence 4", "line1": "Rembrandtplein 20", "city": "Amsterdam", "state": "", "postal_code": "1017 CV", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Amsterdam Residence 5", "line1": "Museumplein 6", "city": "Amsterdam", "state": "", "postal_code": "1071 DJ", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Rotterdam Residence 1", "line1": "Coolsingel 10", "city": "Rotterdam", "state": "", "postal_code": "3011 AD", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Rotterdam Residence 2", "line1": "Lijnbaan 50", "city": "Rotterdam", "state": "", "postal_code": "3012 ER", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Rotterdam Residence 3", "line1": "Witte de Withstraat 30", "city": "Rotterdam", "state": "", "postal_code": "3012 BP", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "The Hague Residence 1", "line1": "Lange Voorhout 10", "city": "The Hague", "state": "", "postal_code": "2514 ED", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "The Hague Residence 2", "line1": "Plein 20", "city": "The Hague", "state": "", "postal_code": "2511 CR", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Utrecht Residence 1", "line1": "Oudegracht 100", "city": "Utrecht", "state": "", "postal_code": "3511 AP", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Utrecht Residence 2", "line1": "Neude 10", "city": "Utrecht", "state": "", "postal_code": "3512 AD", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Eindhoven Residence 1", "line1": "Rechtestraat 50", "city": "Eindhoven", "state": "", "postal_code": "5611 GR", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Eindhoven Residence 2", "line1": "Stratumseind 20", "city": "Eindhoven", "state": "", "postal_code": "5611 ND", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Groningen Residence 1", "line1": "Grote Markt 10", "city": "Groningen", "state": "", "postal_code": "9711 LV", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Groningen Residence 2", "line1": "Herestraat 50", "city": "Groningen", "state": "", "postal_code": "9711 EP", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Maastricht Residence 1", "line1": "Vrijthof 20", "city": "Maastricht", "state": "", "postal_code": "6211 LE", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Maastricht Residence 2", "line1": "Grote Staat 50", "city": "Maastricht", "state": "", "postal_code": "6211 SZ", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Leiden Residence 1", "line1": "Breestraat 100", "city": "Leiden", "state": "", "postal_code": "2311 CS", "country": "NL", "source": "builtin_public", "type": "residential"},
        {"name": "Delft Residence 1", "line1": "Markt 50", "city": "Delft", "state": "", "postal_code": "2611 GS", "country": "NL", "source": "builtin_public", "type": "residential"},

        # 学校/大学 (15条)
        {"name": "Universiteit van Amsterdam", "line1": "Spui 21", "city": "Amsterdam", "state": "", "postal_code": "1012 WX", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Vrije Universiteit Amsterdam", "line1": "De Boelelaan 1105", "city": "Amsterdam", "state": "", "postal_code": "1081 HV", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Universiteit Leiden", "line1": "Rapenburg 70", "city": "Leiden", "state": "", "postal_code": "2311 EZ", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Universiteit Utrecht", "line1": "Heidelberglaan 8", "city": "Utrecht", "state": "", "postal_code": "3584 CS", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Erasmus Universiteit Rotterdam", "line1": "Burgemeester Oudlaan 50", "city": "Rotterdam", "state": "", "postal_code": "3062 PA", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "TU Delft", "line1": "Mekelweg 5", "city": "Delft", "state": "", "postal_code": "2628 CD", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "TU Eindhoven", "line1": "Den Dolech 2", "city": "Eindhoven", "state": "", "postal_code": "5612 AZ", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Rijksuniversiteit Groningen", "line1": "Broerstraat 5", "city": "Groningen", "state": "", "postal_code": "9712 CP", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Universiteit Maastricht", "line1": "Minderbroedersberg 4-6", "city": "Maastricht", "state": "", "postal_code": "6211 LK", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Radboud Universiteit", "line1": "Comeniuslaan 4", "city": "Nijmegen", "state": "", "postal_code": "6525 HP", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Wageningen University", "line1": "Droevendaalsesteeg 4", "city": "Wageningen", "state": "", "postal_code": "6708 PB", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Tilburg University", "line1": "Warandelaan 2", "city": "Tilburg", "state": "", "postal_code": "5037 AB", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "University of Twente", "line1": "Drienerlolaan 5", "city": "Enschede", "state": "", "postal_code": "7522 NB", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Rotterdam Business School", "line1": "Kralingse Zoom 91", "city": "Rotterdam", "state": "", "postal_code": "3063 ND", "country": "NL", "source": "builtin_public", "type": "school"},
        {"name": "Amsterdam Business School", "line1": "Plantage Muidergracht 12", "city": "Amsterdam", "state": "", "postal_code": "1018 TV", "country": "NL", "source": "builtin_public", "type": "school"},

        # 学生宿舍 (8条)
        {"name": "UvA Student Housing", "line1": "Roetersstraat 11", "city": "Amsterdam", "state": "", "postal_code": "1018 WB", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "VU Student Residence", "line1": "De Boelelaan 1109", "city": "Amsterdam", "state": "", "postal_code": "1081 HV", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "Leiden Student Housing", "line1": "Rapenburg 70", "city": "Leiden", "state": "", "postal_code": "2311 EZ", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "Utrecht Student Residence", "line1": "Heidelberglaan 2", "city": "Utrecht", "state": "", "postal_code": "3584 CS", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "EUR Student Housing", "line1": "Burgemeester Oudlaan 50", "city": "Rotterdam", "state": "", "postal_code": "3062 PA", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "TU Delft Student Hall", "line1": "Mekelweg 8", "city": "Delft", "state": "", "postal_code": "2628 CD", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "Groningen Student Housing", "line1": "Broerstraat 5", "city": "Groningen", "state": "", "postal_code": "9712 CP", "country": "NL", "source": "builtin_public", "type": "student"},
        {"name": "Maastricht Student Residence", "line1": "Minderbroedersberg 6", "city": "Maastricht", "state": "", "postal_code": "6211 LK", "country": "NL", "source": "builtin_public", "type": "student"},

        # 办公室/企业 (12条)
        {"name": "Google Netherlands", "line1": "Claude Debussylaan 34", "city": "Amsterdam", "state": "", "postal_code": "1082 MD", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "Microsoft Netherlands", "line1": "Evert van de Beekstraat 354", "city": "Amsterdam", "state": "", "postal_code": "1118 CX", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "Amazon Netherlands", "line1": "Wibautstraat 224", "city": "Amsterdam", "state": "", "postal_code": "1097 DN", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "Facebook Netherlands", "line1": "Burgerweeshuispad 301", "city": "Amsterdam", "state": "", "postal_code": "1076 HR", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "Apple Netherlands", "line1": "Leidseplein 35", "city": "Amsterdam", "state": "", "postal_code": "1017 PS", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "IBM Netherlands", "line1": "Johan Huizingalaan 765", "city": "Amsterdam", "state": "", "postal_code": "1066 VH", "country": "NL", "source": "builtin_public", "type": "office"},
        {"name": "Deloitte Netherlands", "line1": "Gustav Mahlerplein 90", "city": "Amsterdam", "state": "", "postal_code": "1082 MA", "country": "NL", "source": "builtin_public", "type": "company"},
        {"name": "KPMG Netherlands", "line1": "Amstelplein 1", "city": "Amsterdam", "state": "", "postal_code": "1096 HA", "country": "NL", "source": "builtin_public", "type": "company"},
        {"name": "PwC Netherlands", "line1": "Thomas R. Malthusstraat 5", "city": "Amsterdam", "state": "", "postal_code": "1066 JR", "country": "NL", "source": "builtin_public", "type": "company"},
        {"name": "Ernst & Young Netherlands", "line1": "Antonio Vivaldistraat 150", "city": "Amsterdam", "state": "", "postal_code": "1083 HP", "country": "NL", "source": "builtin_public", "type": "company"},
        {"name": "ING Bank", "line1": "Bijlmerplein 888", "city": "Amsterdam", "state": "", "postal_code": "1102 MG", "country": "NL", "source": "builtin_public", "type": "company"},
        {"name": "ABN AMRO", "line1": "Gustav Mahlerlaan 10", "city": "Amsterdam", "state": "", "postal_code": "1082 PP", "country": "NL", "source": "builtin_public", "type": "company"},
    ],
}
